# /etc/logrotate.d/hound-coder
/opt/hound-coder/usage.log {
    weekly
    rotate 26
    compress
    delaycompress
    missingok
    notifempty
    postrotate
        [ -f /run/nginx.pid ] && kill -USR1 "$(cat /run/nginx.pid)"
    endscript
}
